spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/rahulvit32/config-server.git
          default-label: main
          clone-on-start: true


server:
  port: 8888